##配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3306/gulimall_ums?serverTimrzone=GMT
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        group: dev
  application:
    name: gulimall-member
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml
server:
  port: 8000