#配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3306/gulimall_pms?serverTimrzone=GMT
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        group: dev
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
  redis:
    host: 192.168.56.10
    port: 6379
  cache:
    type: redis
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:/mapper/**/*.xml
server:
  port: 10000
logging:
  level:
   com.example.gulimall.product.dao: debug
