spring:
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        group: dev
        namespace: 8c84bf3c-623a-4d24-b34d-5cc0750b8619
    gateway:
      routes:
        - id: test_route
          uri: https://baidu.com
          predicates:
          - Query=url,baidu
        - id: test_route
          uri: https://qq.com
          predicates:
          - Query=url,qq
server:
  port: 88


